# This profile uses the docker-compose DNS names and is activated for the default docker-compose build

spring:
  datasource:
    url: jdbc:postgresql://mls-db:5432/mls-auth?stringtype=unspecified
    username: mls-auth
    password: mls-auth-password
  jpa:
    hibernate:
      ddl-auto: update

application:
  auth:
    signing:
      signing-key: file:/config/keys/dev.key
      renewal-validity: 10080
      request-validity: 5
    verification:
      signing-key: file:/config/keys/dev.pub
  users:
    admin: password

logging:
  config: /config/log-docker.xml
