server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mls-auth?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: mls-auth
    password: mls-auth-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non_contextual_creation: true
          time_zone: UTC

application:
  auth:
    signing:
      signing-key: classpath:dev.key
      renewal-validity: 10080
      request-validity: 5
    verification:
      signing-key: classpath:dev.pub
  users:
    admin: password

logging:
  pattern:
    console: "%d %highlight(%-5level) [%12.12thread] %cyan(%logger{5}): %msg%n"
  level:
    at.wrk.fmd.mls.auth: debug
