name: Build mls-auth-service Docker image

on:
  push:
    branches:
      - master
      - dev

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: wrkfmdit/mls-auth
          tags: |
            type=ref,event=branch
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Create settings file
        run: |
          cat << EOF > /tmp/m2-settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
              <servers>
                  <server>
                      <id>github</id>
                      <username>${GITHUB_ACTOR}</username>
                      <password>${GITHUB_TOKEN}</password>
                  </server>
              </servers>
          </settings>
          EOF
        env:
          GITHUB_TOKEN: "${{ secrets.MLS_PACKAGES_TOKEN }}"

      - name: Build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            MODULE=auth-service
            APP=auth-service
          secret-files: |
            m2-settings=/tmp/m2-settings.xml
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#      - name: Run Docker buildscript
#        run: ./docker-build.sh
#        env:
#          MLS_M2_SETTINGS: "/tmp/m2-settings.xml"
