name: Build mls-auth-service Docker image

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    uses: wrk-fmd/mls-packages/.github/workflows/docker-build.yml@main
    with:
      PROJECT_MODULE: auth-service
      PROJECT_APP: auth-service
      DOCKER_NAME: wrkfmdit/mls-auth
    secrets:
      MLS_PACKAGES_TOKEN: ${{ secrets.MLS_PACKAGES_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
